describe('tempelate spec',()=>{
    it('registration',()=>{
cy.visit('https://automationteststore.com')
cy.contains('login or register').click()
cy.get("[tittle='continiue']").click()
cy.get("accountfrm_firstname").type("luka")
cy.get("#accountfrm_lastname").type("nikolaishvili")
cy.get("#accountfrm_email").type("lukanikolaishvili00@gmail.com")
cy.get("#accountfrm_telephone").type("12345678")
cy.get("#accountfrm_fax").type("1234")
cy.get("#accountfrm_company").type("compania1")
cy.get("#accountfrm_addres_1").type("krtsanisi")
cy.get("#accountfrm_city").typr("tbilisi")
cy.get("#accountfrm_country_id").select(5)
cy.get("#accountfrm_zone_id").select("123")
cy.get("#accountfrm_postcode").type("1100111")
cy.get("#accountfrm_loginname").type("luka12")
cy.get("#accountfrm_password").type("luka12")
cy.get("#accountfrm_confirm").type("luka12")
cy.get("#accountfrm_newsletter0").click()
cy.get("#accountfrm_ageee").click()
cy.get("[title='continue']").click()
 })
 it('edit account details',()=>{
    cy.contains('login or register').click()
    cy.get('#loginfrm_loginname').type('luka12')
    cy.get('#loginfrm_password').type('luka12')
    cy.get('[title="login"]').click()
   
    cy.contains("my account").click()
    cy.contains("edit account details").click({force:frue})
 })
})